// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"kanban-app-playground/internal/adapter"
	"kanban-app-playground/internal/application"
	"kanban-app-playground/internal/infrastructure/sqlite"
)

// Injectors from wire.go:

// InitializeHandler wires all dependencies and returns a ready-to-use Handler.
func InitializeHandler() (*adapter.Handler, func(), error) {
	db, cleanup, err := sqlite.ProvideDB()
	if err != nil {
		return nil, nil, err
	}
	boardRepo := sqlite.NewBoardRepo(db)
	columnRepo := sqlite.NewColumnRepo(db)
	cardRepo := sqlite.NewCardRepo(db)
	boardService := application.NewBoardService(boardRepo, columnRepo, cardRepo)
	columnService := application.NewColumnService(columnRepo, cardRepo)
	cardService := application.NewCardService(cardRepo, columnRepo)
	handler := adapter.NewHandler(boardService, columnService, cardService)
	return handler, func() {
		cleanup()
	}, nil
}
