// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBoard(arg1) {
  return window['go']['adapter']['Handler']['CreateBoard'](arg1);
}

export function CreateCard(arg1, arg2) {
  return window['go']['adapter']['Handler']['CreateCard'](arg1, arg2);
}

export function CreateColumn(arg1, arg2) {
  return window['go']['adapter']['Handler']['CreateColumn'](arg1, arg2);
}

export function DeleteBoard(arg1) {
  return window['go']['adapter']['Handler']['DeleteBoard'](arg1);
}

export function DeleteCard(arg1) {
  return window['go']['adapter']['Handler']['DeleteCard'](arg1);
}

export function DeleteColumn(arg1, arg2) {
  return window['go']['adapter']['Handler']['DeleteColumn'](arg1, arg2);
}

export function FilterCards(arg1, arg2) {
  return window['go']['adapter']['Handler']['FilterCards'](arg1, arg2);
}

export function GetAllBoards() {
  return window['go']['adapter']['Handler']['GetAllBoards']();
}

export function GetBoardWithData(arg1) {
  return window['go']['adapter']['Handler']['GetBoardWithData'](arg1);
}

export function MoveCard(arg1, arg2, arg3) {
  return window['go']['adapter']['Handler']['MoveCard'](arg1, arg2, arg3);
}

export function MoveColumn(arg1, arg2) {
  return window['go']['adapter']['Handler']['MoveColumn'](arg1, arg2);
}

export function SearchCards(arg1, arg2) {
  return window['go']['adapter']['Handler']['SearchCards'](arg1, arg2);
}

export function SeedIfEmpty(arg1) {
  return window['go']['adapter']['Handler']['SeedIfEmpty'](arg1);
}

export function UpdateBoard(arg1, arg2) {
  return window['go']['adapter']['Handler']['UpdateBoard'](arg1, arg2);
}

export function UpdateCard(arg1, arg2) {
  return window['go']['adapter']['Handler']['UpdateCard'](arg1, arg2);
}

export function UpdateColumn(arg1, arg2) {
  return window['go']['adapter']['Handler']['UpdateColumn'](arg1, arg2);
}
