// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {application} from '../models';

export function CreateBoard(arg1:string):Promise<domain.Board>;

export function CreateCard(arg1:string,arg2:string):Promise<domain.Card>;

export function CreateColumn(arg1:string,arg2:string):Promise<domain.Column>;

export function DeleteBoard(arg1:string):Promise<void>;

export function DeleteCard(arg1:string):Promise<void>;

export function DeleteColumn(arg1:string,arg2:string):Promise<void>;

export function FilterCards(arg1:string,arg2:string):Promise<application.BoardData>;

export function GetAllBoards():Promise<Array<domain.Board>>;

export function GetBoardWithData(arg1:string):Promise<application.BoardData>;

export function MoveCard(arg1:string,arg2:string,arg3:number):Promise<void>;

export function MoveColumn(arg1:string,arg2:number):Promise<void>;

export function SearchCards(arg1:string,arg2:string):Promise<Array<domain.Card>>;

export function UpdateBoard(arg1:string,arg2:string):Promise<domain.Board>;

export function UpdateCard(arg1:string,arg2:domain.CardUpdate):Promise<domain.Card>;

export function UpdateColumn(arg1:string,arg2:string):Promise<domain.Column>;
